### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [azatnv/Polinom#1]
1. Замените внутреннее представление полинома. Преобразовывать полином при каждой операции странно и неэффективно. Преобразование из строки оставьте только в конструкторе.
2. Добавьте метод для полученения коэффициентов полинома и конструктор из коэффициентов.

**Comment by azatnv** [comment]
Исправил

**Comment by gagarski** [comment]
Сейчас лишними бы не были тесты для конструктора полинома из строки.
